package io.roax.canon

import java.security.SecureRandom

/**
 * ROAX-CANON/1 section 7: `salt(leaf) = 16 bytes drawn from a CSPRNG, independently for every leaf`.
 *
 * There is no derivation, no key derivation function, no master secret and no preimage. Decision D4
 * was ruled D4b, and the reasoning is worth keeping next to the code because the deleted option is
 * the one a reader is most likely to reinvent: reusing a master salt across two records for the
 * same patient makes every shared path with a shared value produce the *same* leaf hash in both,
 * so anyone who sees both disclosures links them - and both records still verify perfectly, so
 * nothing reports a problem.
 *
 * **Salts are generated by the protocol, not supplied by the issuing institution.** They are not
 * clinical data and impose no data-collection burden on any issuer.
 */
fun interface SaltSource {
    /** Returns exactly [SALT_LENGTH_BYTES] fresh bytes. */
    fun next(): ByteArray

    companion object {
        /**
         * The default: one [SecureRandom] drawn from independently for every leaf.
         *
         * The 128-bit entropy floor is normative and load-bearing - it is the only thing standing
         * between a withheld low-entropy leaf and a dictionary search (section 10.1). A salt from a
         * non-cryptographic generator silently removes that protection while every verification
         * still passes, which is why this is not a pluggable `Random`.
         */
        fun secureRandom(): SaltSource {
            val rng = SecureRandom()
            return SaltSource {
                val b = ByteArray(SALT_LENGTH_BYTES)
                rng.nextBytes(b)
                b
            }
        }

        /**
         * Replays a fixed sequence, for reproducing a committed root from a committed salt set.
         *
         * This is not a generator and must never be used to issue: under D4b a salt is an
         * independent random draw that nothing can re-derive, so a committed corpus vector has to
         * name the set its root was computed under.
         */
        fun replaying(salts: List<ByteArray>): SaltSource {
            val it = salts.iterator()
            return SaltSource {
                if (!it.hasNext()) fail(Reason.SALT_MISSING_FOR_LEAF, "replay source exhausted")
                it.next()
            }
        }
    }
}
