/**
 * Issuance and selective disclosure.
 *
 * Issuance draws every salt itself, from a CSPRNG, and produces a full copy. Disclosure takes a
 * full copy and a set of paths to reveal, and produces a disclosed copy carrying the salt of every
 * revealed leaf and the salt of no other.
 *
 * > **Salts are generated by the protocol, not supplied by the issuing institution.**
 * > Salts are not clinical data, not a record field, and not something a hospital, a laboratory or
 * > any other issuer collects or stores in its own systems (specification section 7).
 * >
 * > Requiring a full copy to carry every salt therefore imposes NO new data-collection burden on
 * > any issuer. "Include the random numbers in the dataset" is an easy and expensive misreading.
 */

import { fail } from './errors.js';
import { toHex } from './bytes.js';
import { encodePath, displayPath, type Path } from './path.js';
import { resolveHashFunction, CANON_VERSION, type HashAlgName } from './hash.js';
import { commitRecord, FreshSalts, type Commitment } from './commit.js';
import type { RecordIdentity } from './reserved.js';
import { TypeTag, type CarrierValue } from './value.js';
import type { EmptyContainerPolicy } from './flatten.js';
import type { TypeTagResolver } from './typemap.js';
import type { JsonValue } from './json.js';
import { floorFor } from './profiles.js';
import { mandatoryReservedPaths } from './reserved.js';

export interface IssueOptions {
  readonly record: JsonValue;
  readonly identity: RecordIdentity;
  readonly resolver: TypeTagResolver;
  readonly hashAlg?: HashAlgName | undefined;
  /** The type-map artifact version, carried beside its ID in the envelope's discovery hint. */
  readonly typeMapVersion?: string | undefined;
  readonly anchor?:
    | { readonly chainId: number; readonly registry: string; readonly txHash?: string | undefined }
    | undefined;
  readonly emptyContainerPolicy?: EmptyContainerPolicy | undefined;
}

export interface FullCopy {
  /** The envelope as a value tree, ready for `writeJson`. */
  readonly document: JsonValue;
  readonly commitment: Commitment;
  readonly identity: RecordIdentity;
  readonly hashAlg: HashAlgName;
  readonly root: string;
}

/**
 * Issues a full copy.
 *
 * Every salt is drawn here, independently, from `node:crypto`. Reissuing the same record produces
 * a DIFFERENT root, and that is the point: reusing salts across a reissuance is exactly the
 * cross-record patient-linkage hazard decision D4b was ruled to remove (specification section 7.1).
 */
export function issueFullCopy(options: IssueOptions): FullCopy {
  const hashAlg: HashAlgName = options.hashAlg ?? 'SHA-256';
  const hash = resolveHashFunction(hashAlg);

  // `schemas/envelope-2.0.json` requires the type-map binding, and issuance is the current
  // version's path. Verification still reads an envelope-1.0 document, where the member is absent.
  if (options.identity.typeMapId === undefined) {
    fail(
      'envelope-malformed',
      'issuance requires the exact type-map artifact ID, which is committed at ' +
        'roax.typeMap.id and carried in the envelope (specification sections 4.2 and 11.2)',
    );
  }

  const commitment = commitRecord(options.record, {
    hash,
    resolver: options.resolver,
    identity: options.identity,
    salts: new FreshSalts(),
    emptyContainerPolicy: options.emptyContainerPolicy,
  });

  for (const leaf of commitment.leaves) {
    // Section 6.5: an implementation MUST reject a record whose type map binds any path to tag 8
    // until a profile declares the binding. Checked at issuance as well as at map-compile time,
    // because a resolver this library did not compile could still return it.
    if (leaf.tag === TypeTag.BLOB_REF) {
      fail(
        'blob-ref-not-selectable',
        `the leaf at ${displayPath(leaf.path)} resolves to tag 8 BLOB_REF, which no version-1 ` +
          'profile selects',
      );
    }
  }

  const members: [string, JsonValue][] = [
    ['canon', { kind: 'string', value: CANON_VERSION }],
    ['hashAlg', { kind: 'string', value: hashAlg }],
    ['recordType', { kind: 'string', value: options.identity.recordType }],
    ['schemaVersion', { kind: 'string', value: options.identity.schemaVersion }],
    [
      'typeMap',
      {
        kind: 'object',
        members: [
          ['id', { kind: 'string', value: options.identity.typeMapId }],
          ['version', { kind: 'string', value: options.typeMapVersion ?? '1.0.0' }],
        ],
      },
    ],
    ['recordId', { kind: 'string', value: options.identity.recordId }],
    ['root', { kind: 'string', value: toHex(commitment.root) }],
    ['leafCount', { kind: 'number', literal: String(commitment.leafCount) }],
    ['issuer', issuerNode(options.identity)],
  ];
  if (options.anchor !== undefined) {
    // OUTSIDE the root: a routing hint and never authority (specification section 11.3).
    const anchorMembers: [string, JsonValue][] = [
      ['chainId', { kind: 'number', literal: String(options.anchor.chainId) }],
      ['registry', { kind: 'string', value: options.anchor.registry }],
    ];
    if (options.anchor.txHash !== undefined) {
      anchorMembers.push(['txHash', { kind: 'string', value: options.anchor.txHash }]);
    }
    members.push(['anchor', { kind: 'object', members: anchorMembers }]);
  }
  members.push(['record', options.record]);
  members.push([
    // Rule 1 of section 7.3: a full copy MUST carry the salt of EVERY leaf of the union, addressed
    // by its structured path. Without it a full copy is not verifiable at all.
    'salts',
    {
      kind: 'array',
      items: commitment.leaves.map(
        (leaf): JsonValue => ({
          kind: 'object',
          members: [
            ['segments', segmentsNode(leaf.path)],
            ['salt', { kind: 'string', value: toHex(leaf.salt) }],
          ],
        }),
      ),
    },
  ]);

  return {
    document: { kind: 'object', members },
    commitment,
    identity: options.identity,
    hashAlg,
    root: toHex(commitment.root),
  };
}

function issuerNode(identity: RecordIdentity): JsonValue {
  const members: [string, JsonValue][] = [['id', { kind: 'string', value: identity.issuerId }]];
  if (identity.issuerKeyId !== undefined) {
    members.push(['keyId', { kind: 'string', value: identity.issuerKeyId }]);
  }
  return { kind: 'object', members };
}

function segmentsNode(path: Path): JsonValue {
  return {
    kind: 'array',
    items: path.map(
      (s): JsonValue =>
        'key' in s
          ? { kind: 'object', members: [['key', { kind: 'string', value: s.key }]] }
          : {
              kind: 'object',
              members: [['index', { kind: 'number', literal: String(s.index) }]],
            },
    ),
  };
}

export interface DiscloseOptions {
  /** The paths to reveal, as SEGMENTS. A display path is never accepted here (section 5.2). */
  readonly reveal: readonly Path[];
  /** Include the human-readable display path on each disclosed leaf. Display only. */
  readonly includeDisplayPath?: boolean | undefined;
}

/**
 * Downgrades a full copy to a disclosed copy.
 *
 * The `salts` array is DROPPED and each revealed leaf carries its own salt alone. That is the
 * whole security property: a disclosed copy that shipped every salt would still verify correctly
 * against the root, pass every inclusion proof, and leak every withheld field to a dictionary
 * search, with nothing about the verification result indicating a problem (section 10.1).
 *
 * The minimum-disclosure floor is enforced HERE as well as at verification, and the guarantee that
 * buys is exactly this: **for a `recordType` in `PROFILE_FLOORS`, a holder cannot produce a copy
 * that a conforming verifier rejects for omitting a non-redactable path.**
 *
 * It is stated that narrowly because it is not wider. For a `recordType` the registry does not
 * carry, `floorFor` returns `undefined`, this function contributes the mandatory RESERVED paths
 * and no profile paths, and the copy is produced - while `verifyEnvelope` fails it closed with
 * `profile-unknown` under specification section 12.2, on its own profile allow-list. That is
 * reachable today with `org.roax.corpus.synthetic`, which `issueFullCopy` deliberately permits.
 *
 * Failing closed here instead would be the wrong repair: it would refuse disclosure for every
 * unregistered `recordType` that issuance intentionally allows, and the profile allow-list belongs
 * to the VERIFIER rather than to the holder - a verifier configured with the corpus profile
 * accepts the same copy (see `corpusVerifierConfig` in the conformance runner).
 */
export function discloseFrom(full: FullCopy, options: DiscloseOptions): JsonValue {
  const byPath = new Map(full.commitment.leaves.map((l) => [toHex(encodePath(l.path)), l]));

  const revealKeys = new Set<string>();
  for (const path of options.reveal) {
    const key = toHex(encodePath(path));
    if (!byPath.has(key)) {
      fail(
        'envelope-malformed',
        `the record has no leaf at ${displayPath(path)}, so it cannot be disclosed`,
      );
    }
    revealKeys.add(key);
  }

  // The floor is the mandatory reserved paths plus whatever the profile adds
  // (specification section 10.2). `roax.issuer.keyId` is NOT in it, even when committed.
  const floor = floorFor(full.identity.recordType);
  const floorPaths: Path[] = [
    ...mandatoryReservedPaths(full.identity),
    ...(floor?.profilePaths ?? []),
  ];
  for (const path of floorPaths) {
    const key = toHex(encodePath(path));
    if (!revealKeys.has(key)) {
      fail(
        'minimum-disclosure-floor',
        `a disclosed copy MUST reveal the non-redactable path ${displayPath(path)}`,
      );
    }
  }

  const leaves: JsonValue[] = [];
  for (const key of revealKeys) {
    const leaf = byPath.get(key);
    if (leaf === undefined) {
      continue;
    }
    const members: [string, JsonValue][] = [['segments', segmentsNode(leaf.path)]];
    if (options.includeDisplayPath === true) {
      members.push(['displayPath', { kind: 'string', value: displayPath(leaf.path) }]);
    }
    members.push(['index', { kind: 'number', literal: String(leaf.index) }]);
    members.push(['tag', { kind: 'number', literal: String(leaf.tag) }]);
    if (leaf.value !== undefined) {
      members.push(['value', carrierNode(leaf.value)]);
    }
    members.push(['salt', { kind: 'string', value: toHex(leaf.salt) }]);
    members.push([
      'auditPath',
      {
        kind: 'array',
        items: full.commitment
          .auditPathFor(leaf.index)
          .map((h): JsonValue => ({ kind: 'string', value: toHex(h) })),
      },
    ]);
    leaves.push({ kind: 'object', members });
  }

  const source = full.document;
  if (source.kind !== 'object') {
    fail('envelope-malformed', 'the full copy is not an object');
  }
  const members: [string, JsonValue][] = [];
  for (const [name, value] of source.members) {
    // `record` and `salts` are the full-copy members and both are dropped. Dropping `salts` is
    // what makes a withheld leaf's salt UNREPRESENTABLE rather than merely prohibited.
    if (name === 'record' || name === 'salts') {
      continue;
    }
    members.push([name, value]);
  }
  members.push([
    'disclosure',
    {
      kind: 'object',
      members: [
        ['mode', { kind: 'string', value: 'selective' }],
        ['leaves', { kind: 'array', items: leaves }],
      ],
    },
  ]);
  return { kind: 'object', members };
}

function carrierNode(value: CarrierValue): JsonValue {
  if (typeof value === 'boolean') {
    return { kind: 'boolean', value };
  }
  if (typeof value === 'string') {
    // INTEGER and DECIMAL travel as STRINGS in an envelope, exactly as they do in a corpus vector:
    // writing the literal as a JSON number would hand the next reader's parser the chance to
    // destroy it (specification section 6.4).
    return { kind: 'string', value };
  }
  return {
    kind: 'object',
    members: [
      ['blobByteLength', { kind: 'string', value: value.blobByteLength }],
      ['blobDigest', { kind: 'string', value: value.blobDigest }],
    ],
  };
}
